apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- snapshot.yaml
- eraser.yaml
- descheduler.yaml
- kube-fledged.yaml
- reflector.yaml
- reloader.yaml
- sealed.yaml

namespace: argocd

commonLabels:
  app.kubernetes.io/category: utilities
