apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/stepanovdg/homelab.git'
    path: apps/utilities/sealed-secrets
    targetRevision: master
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    - Validate=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
