apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/truenas/charts/tree/master/community/jellyfin
    chart: jellyfin
    targetRevision: 1.2.6
    helm:
      releaseName: jellyfin
      values: |
        global:
          ixChartContext:
            addNvidiaRuntimeClass: false
            hasNFSCSI: true
            hasSMBCSI: true
            isInstall: true
            isStopped: false
            isUpdate: false
            isUpgrade: false
            kubernetes_config:
              cluster_cidr: 172.16.0.0/16
              cluster_dns_ip: 172.17.0.10
              service_cidr: 172.17.0.0/16
            nfsProvisioner: nfs.csi.k8s.io
            nvidiaRuntimeClassName: nvidia
            operation: INSTALL
            smbProvisioner: smb.csi.k8s.io
            storageClassName: ix-storage-class-jellyfin
            upgradeMetadata: {}
        image:
          pullPolicy: IfNotPresent
          repository: jellyfin/jellyfin
          tag: 10.8.13
        ixCertificateAuthorities: {}
        ixCertificates: {}
        ixChartContext:
          addNvidiaRuntimeClass: false
          hasNFSCSI: true
          hasSMBCSI: true
          isInstall: true
          isStopped: false
          isUpdate: false
          isUpgrade: false
          kubernetes_config:
            cluster_cidr: 172.16.0.0/16
            cluster_dns_ip: 172.17.0.10
            service_cidr: 172.17.0.0/16
          nfsProvisioner: nfs.csi.k8s.io
          nvidiaRuntimeClassName: nvidia
          operation: INSTALL
          smbProvisioner: smb.csi.k8s.io
          storageClassName: ix-storage-class-jellyfin
          upgradeMetadata: {}
        ixExternalInterfacesConfiguration: []
        ixExternalInterfacesConfigurationNames: []
        ixVolumes: []
        jellyfinConfig:
          additionalEnvs: []
          publishServerUrl: ""
          publishedServerUrl: ""
        jellyfinGPU:
          amd.com/gpu: 0
          gpu.intel.com/i915: 0
          nvidia.com/gpu: 0
        jellyfinNetwork:
          hostNetwork: true
          webPort: 30013
        jellyfinRunAs:
          group: 1000
          user: 1000
        jellyfinStorage:
          additionalStorages:
            - hostPathConfig:
                aclEnable: false
                hostPath: /mnt/Utility/Media/data
              mountPath: /media
              readOnly: false
              type: hostPath
          cache:
            hostPathConfig:
              aclEnable: false
              hostPath: /mnt/Utility/Media/config/jellyfin/cache
            ixVolumeConfig:
              datasetName: cache
            type: hostPath
          config:
            hostPathConfig:
              aclEnable: false
              hostPath: /mnt/Utility/Media/config/jellyfin
            ixVolumeConfig:
              datasetName: config
            type: hostPath
          transcodes:
            hostPathConfig:
              aclEnable: false
              hostPath: /mnt/Utility/Media/transcode
            ixVolumeConfig:
              datasetName: transcodes
            type: hostPath
        release_name: jellyfin
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi

  destination:
    namespace: media
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 60m
