apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
#    repoURL: https://github.com/truecharts/charts
    repoURL: https://github.com/truenas/charts/tree/master/charts/plex
    chart: plex
    targetRevision: 1.7.59
#    targetRevision: 16.1.5
    helm:
      releaseName: plex
      values: |
        appVolumeMounts:
          config:
            hostPath: /mnt/Utility/Media/config/plex
            hostPathEnabled: true
            mountPath: /config
          data:
            hostPath: /mnt/Utility/Media/data
            hostPathEnabled: true
            mountPath: /data
          shared:
            emptyDir: true
            mountPath: /shared
          shared-logs:
            emptyDir: true
            mountPath: /config/Library/Application Support/Plex Media Server/Logs
          transcode:
            hostPath: /mnt/Utility/Media/transcode
            hostPathEnabled: true
            mountPath: /transcode
        claimToken: claim-gsUJsH-A-9v8MwzQUCm8
        dnsConfig:
          options: []
        enablePlexPass: true
        enableResourceLimits: false
        environmentVariables: []
        extraAppVolumeMounts: []
        global:
          ixChartContext:
            addNvidiaRuntimeClass: false
            hasNFSCSI: true
            hasSMBCSI: true
            isInstall: true
            isStopped: false
            isUpdate: false
            isUpgrade: false
            kubernetes_config:
              cluster_cidr: 172.16.0.0/16
              cluster_dns_ip: 172.17.0.10
              service_cidr: 172.17.0.0/16
            nfsProvisioner: nfs.csi.k8s.io
            nvidiaRuntimeClassName: nvidia
            operation: INSTALL
            smbProvisioner: smb.csi.k8s.io
            storageClassName: ix-storage-class-plex
            upgradeMetadata: {}
        gpuConfiguration:
          amd.com/gpu: 0
          gpu.intel.com/i915: 0
          nvidia.com/gpu: 0
        hostNetwork: true
        image:
          pullPolicy: IfNotPresent
          repository: plexinc/pms-docker
          tag: 1.32.8.7639-fb6452ebf
        ixCertificateAuthorities: {}
        ixCertificates: {}
        ixChartContext:
          addNvidiaRuntimeClass: false
          hasNFSCSI: true
          hasSMBCSI: true
          isInstall: true
          isStopped: false
          isUpdate: false
          isUpgrade: false
          kubernetes_config:
            cluster_cidr: 172.16.0.0/16
            cluster_dns_ip: 172.17.0.10
            service_cidr: 172.17.0.0/16
          nfsProvisioner: nfs.csi.k8s.io
          nvidiaRuntimeClassName: nvidia
          operation: INSTALL
          smbProvisioner: smb.csi.k8s.io
          storageClassName: ix-storage-class-plex
          upgradeMetadata: {}
        ixExternalInterfacesConfiguration: []
        ixExternalInterfacesConfigurationNames: []
        ixVolumes: []
        plexServiceTCP:
          port: 32400
        plexpassImage:
          pullPolicy: IfNotPresent
          repository: plexinc/pms-docker
          tag: plexpass
        release_name: plex
        timezone: America/Los_Angeles
        updateStrategy: Recreate
  destination:
    namespace: media
    name: truenas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=false
      - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 60m
