apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/stepanovdg/homelab.git'
    path: apps/services/homepage
    targetRevision: master
  destination:
    namespace: services
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - Prune=true
    - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
