apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-configuration
  namespace: argocd
spec:
  encryptedData:
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: vault-configuration
      namespace: argocd
    type: Opaque
