apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  description: Applications General Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: databases
    server: https://kubernetes.default.svc
  - namespace: vault
    server: https://kubernetes.default.svc
  - namespace: services
    server: https://kubernetes.default.svc
  - namespace: media
    name: truenas
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
