apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dashboard.stepanovs.dev
  dnsNames:
  - dashboard.stepanovs.dev
