apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-cert
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: grafana.stepanovs.dev
  dnsNames:
  - grafana.stepanovs.dev
