apiVersion: v1
kind: Endpoints
metadata:
  name: k3s-metrics-service
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.5.6.101
  - ip: 10.5.6.102
  - ip: 10.5.6.103
  - ip: 10.5.6.121
  - ip: 10.5.6.122
  - ip: 10.5.6.123
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
