apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: stepanovdg@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector:
        dnsNames:
        - '*.stepanovs.dev'
      dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-token
            key: access-token
