apiVersion: v1
kind: ConfigMap
metadata:
  name: eraser-manager-config
  namespace: eraser-system
data:
  controller_manager_config.yaml: |
    apiVersion: eraser.sh/v1alpha2
    kind: EraserConfig
    manager:
      runtime: containerd
      otlpEndpoint: ""
      logLevel: info
      scheduling:
        repeatInterval: 24h
        beginImmediately: true
      profile:
        enabled: false
        port: 6060
      imageJob:
        successRatio: 1.0
        cleanup:
          delayOnSuccess: 0s
          delayOnFailure: 24h
      nodeFilter:
        type: exclude
        selectors:
          - eraser.sh/cleanup.filter
          - kubernetes.io/os=windows
    components:
      collector:
        enabled: true
        image:
          repo: ghcr.io/eraser-dev/collector
          tag: v1.2.1
        request:
          mem: 25Mi
          cpu: 7m
        limit:
          mem: 500Mi
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run
          cpu: 0
      scanner:
        enabled: false
      remover:
        image:
          repo: ghcr.io/eraser-dev/remover
          tag: v1.2.1
        request:
          mem: 25Mi
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run
          cpu: 0
        limit:
          mem: 30Mi
          cpu: 0
