apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  labels:
    app.kubernetes.io/category: services
spec:
  project: apps
  source:
    repoURL: 'https://github.com/stepanovdg/homelab.git'
    path: apps/argocd/base/media
    targetRevision: master
  destination:
    namespace: media
    name: truenas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        prometheus: enabled
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m